### ISSUE TITLE
[BUG] Issue with companion recommendations

### ISSUE THREAD

**Issue by sivaavkd** [fabric8-analytics/fabric8-analytics-vscode-extension#317]
**Describe the bug**
In companion recommendation, some packages like 'request' and 'pyyaml' coming regularly with the range 94-96% and 56-59% respectively.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If applicable, attach logs.

**VSCode(please complete the following information):**
 - OS: [e.g. macOS]
 - VSCode version [e.g. 1.33.1]
 - Dependency Analytics Version [e.g. 0.0.22]

**CHE7/Theia(please complete the following information):**
 - OS: [e.g. macOS]
 - Browser [e.g. chrome]
 - CHE/Theia version 
 - Dependency Analytics Version [e.g. 0.0.22]

**Additional context**
@lucky-suman @anuragtr

**Comment by lucky-suman** [comment]
Hello, This bug occurred because of Python Path in IDE. So, can be solved by set the PythonPath in the VSCode. Just follow this for VSCode:

1. Go to File->Preferences->Settings
2. Search 'python.pythonPath' and update it.

Write 'python' or 'python3' and it will automatically update the path. Then restart VSCode and it will give recommendations according to given stack.
