### ISSUE TITLE
[BUG] cannot contribute: npm install fails with 401 Unauthorized

### ISSUE THREAD

**Issue by fbauzac** [fabric8-analytics/fabric8-analytics-vscode-extension#713]
**Describe the bug**
Hello,

I would like to rebuild this project on my computer.  To do that, I
have installed the latest Node, upgraded npm to the latest version,
made sure I have created an account on NPM and did a "npm login", and
I have run "npm install" from the project root directory.

However, it fails:

fabric8-analytics-vscode-extension$ npm install
npm error code E401
npm error 401 Unauthorized - GET https://npm.pkg.github.com/download/@RHEcosystemAppEng/exhort-javascript-api/0.1.1-ea.14/b7f01baf0e01d8d697a2b5264e4f374d001004fd - authentication token not provided
npm error A complete log of this run can be found in: .../.npm/_logs/2024-05-17T20_48_17_618Z-debug-0.log

I have tried to gather more information on this package by checking if
I could find it with my browser:

https://www.npmjs.com/search?q=exhort-javascript-api

but it returned no results.  Is this package inaccessible to mere
mortals?

If this package should be public but is not by mistake, could you
please fix it and make it public?

On the contrary, if this package is not meant to be public, and
contributors are limited to e.g. Red Hat staff, then could you please
say so in CONTRIBUTING?

Thanks!

Best regards
Fabrice

**To Reproduce**
- Download and unpack node-v20.13.1-linux-x64.tar.xz
- add the bin/ subdirectory to the PATH env var
- upgrade npm: npm install npm@latest -g
- Clone this project (version: v0.9.4 ca4be57ac77ac618e052f2b3e92c2174eabbd393)
- Run "npm install" as indicated in CONTRIBUTING.md
- it fails with the error above.

**Expected behavior**
"npm install" should install the dependencies without error.

**Logs**
I will attach the log: 2024-05-17T20_48_17_618Z-debug-0.log
[2024-05-17T20_48_17_618Z-debug-0.log](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/files/15358261/2024-05-17T20_48_17_618Z-debug-0.log)

**VSCode(please complete the following information):**
Version: 1.89.1
Commit: dc96b837cf6bb4af9cd736aa3af08cf8279f7685
Date: 2024-05-07T05:16:23.416Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Linux x64 6.5.0-35-generic

Dependency Analytics Version (which I did not build): 0.9.4

**Additional context**
OS: Ubuntu 22.04.4 LTS

**Comment by IlonaShishov** [comment]
Hello @fbauzac ,

Thank you for your detailed report and for your interest in contributing to the project.

The exhort-javascript-api package you mentioned is currently not publicly accessible because it's intended for internal use by our engineering team at Red Hat. At this time, we do not allow external contributions due to ongoing work being performed on the code by our engineers.

I apologize for any inconvenience this may cause. To prevent further confusion, I will update the CONTRIBUTING.md file to clearly state that contributions from external developers are not accepted at this moment. This should help set the right expectations for anyone looking to contribute in the future.

Thank you for bringing this to our attention, and for your understanding.
